language: node_js
node_js:
  - 14

services: 
  - docker

before_install:
  - docker build -t rwijupal3058/docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true -p 3000:30000 rwijupal3058/docker_react 
  

